name: PR comment about lint & format codes
run-name: PR comment about lint & format codes
on: [pull_request]
jobs:
  ruff-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Check Lint and Format
        id: ruff
        run: |
          ruff check .
          ruff format . --check
        continue-on-error: true
      - name: Lint with Ruff
        if: ${{ steps.ruff.outcome == 'failure' }}
        run: |
          ruff check . --fix
          ruff format .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: ruff
