name: lint & format codes
run-name: lint & format by ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install ruff
      - run: |
          ruff check .
          ruff fix .
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style fixes by ruff"
